"""make coach team_id nullable

Revision ID: 877cb77f1a6e
Revises: 3382fa48c863
Create Date: 2026-05-05 15:08:10.322140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877cb77f1a6e'
down_revision = '3382fa48c863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
